server:
  address: 0.0.0.0
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: c3-server
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
